query allWorks {
  projects {
    id
    projectName
    resume
    description
    uiDesign
    uxDesign
    frontend
    backend
    deployment
    challenges
    toolsUsed
    techStack
    websiteUrl
    thumbnailCloudinary
    uiDesignCloudinary
    uxDesignCloudinary
  }
}